on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true
      - name: Use dummy .env file
        run: cp .env.example .env
      - name: Check formatting
        run: pnpm prettier . --check
