on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - name: Use default .env file
        run: cp .env.example .env
        run: pnpm test
      - name: Run tests
        run: pnpm test
